[theme]
primaryColor = "#3498db"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#000000"
font = "sans serif"
baseFontSize = 12
baseRadius = "0.25rem"

[server]
runOnSave = true

[browser]
gatherUsageStatus = false